import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",

    // Generated by Contentlayer:
    ".contentlayer/**",
  ]),
  {
    files: ["app/blog/**/*.tsx"],
    rules: {
      // Allow contentlayer's useMDXComponent pattern which creates components during render
      // This is the standard pattern for contentlayer and is safe
      "@next/next/no-img-element": "warn", // Allow img in MDX content
    },
  },
]);

export default eslintConfig;
